### ISSUE TITLE
Handle SIGPIPE - using fltn with head raises an error

### ISSUE THREAD

**Issue by dufferzafar** [nickjer/fltn#1]
```
❯ fltn /large/json/file | head -n 1
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1017:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dufferzafar** [comment]
This is because: https://github.com/rust-lang/rust/issues/62569

**Comment by dufferzafar** [comment]
As suggested by BurntSushi, can be fixed: https://stackoverflow.com/questions/65755853/simple-word-count-rust-program-outputs-valid-stdout-but-panicks-when-piped-to-he/65760807#65760807

**Comment by dufferzafar** [comment]
Commit in another Rust application fixing this error: https://github.com/crev-dev/cargo-crev/commit/3f3dedf8428a054072492401a086c51c82a08215

**Comment by nickjer** [comment]
Oh, thanks for the helpful links. I might not be able to dig into this until this weekend, but looks fairly straightforward to fix as I just need to bubble up the error from the `println!`.

**Comment by nickjer** [comment]
I had some free time tonight and I found it interesting. So this should be fixed by:

https://github.com/nickjer/fltn/commit/1bb749edcc8b07c914161c0d2a17a895fb8336f6
